import { BookItem, LegalCategory } from '@/types/library';

// Gambar Sampul Akademis HD Terkurasi
const COVERS = {
  tataNegara: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=800&auto=format&fit=crop',
  pidana: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?q=80&w=800&auto=format&fit=crop',
  perdata: 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?q=80&w=800&auto=format&fit=crop',
  acara: 'https://images.unsplash.com/photo-1436450412740-6b988f486c6b?q=80&w=800&auto=format&fit=crop',
  agraria: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=800&auto=format&fit=crop',
  administrasi: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
  lingkungan: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=800&auto=format&fit=crop',
  politik: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?q=80&w=800&auto=format&fit=crop',
  internasional: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
};

// Database Curated 50+ Koleksi Buku Hukum & Politik Nyata
const FULL_LEGAL_DATABASE: BookItem[] = [
  // --- HUKUM NASIONAL (20 BUKU) ---
  {
    id: 'hn-01',
    title: 'Hukum Tata Negara Indonesia: Tinjauan Komprehensif',
    authors: ['Prof. Dr. Jimly Asshiddiqie, S.H.'],
    publisher: 'Rajawali Pers',
    publishedDate: '2023',
    description: 'Buku rujukan utama mengenai struktur ketatanegaraan Indonesia, lembaga negara, serta dinamika konstitusi pasca-reformasi.',
    isbn: '978-602-425-112-3',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Tata Negara',
    coverUrl: COVERS.tataNegara,
    pageCount: 520,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-01 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-02',
    title: 'Asas-Asas Hukum Pidana Indonesia & Perkembangannya',
    authors: ['Prof. Moeljatno, S.H.'],
    publisher: 'Rineka Cipta',
    publishedDate: '2022',
    description: 'Pembahasan mendalam mengenai teori kejahatan, pertanggungjawaban pidana, asas legalitas, dan analisis KUHP Baru No. 1/2023.',
    isbn: '978-979-518-301-4',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Pidana',
    coverUrl: COVERS.pidana,
    pageCount: 380,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-02 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-03',
    title: 'Hukum Perdata Indonesia: Sistem Praktis & Jurisprudensi',
    authors: ['Subekti, S.H.'],
    publisher: 'Intermasa',
    publishedDate: '2021',
    description: 'Panduan utama hukum perjanjian, perikatan, hukum benda, dan hukum perorangan sesuai dengan BW / KUHPerdata Indonesia.',
    isbn: '978-979-8114-15-2',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Perdata',
    coverUrl: COVERS.perdata,
    pageCount: 410,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-03 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-04',
    title: 'Hukum Acara Pidana (Sistem Peradilan Pidana)',
    authors: ['M. Yahya Harahap, S.H.'],
    publisher: 'Sinar Grafika',
    publishedDate: '2023',
    description: 'Pembahasan lengkap KUHAP, penyidikan, penuntutan, persidangan, hingga upaya hukum banding dan kasasi di Mahkamah Agung.',
    isbn: '978-602-092-211-8',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Acara Pidana',
    coverUrl: COVERS.acara,
    pageCount: 680,
    language: 'id',
    availability: 'DIPINJAM',
    shelfLocation: 'Rak H-04 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-05',
    title: 'Hukum Agraria Indonesia: Sejarah & UU Pokok Agraria',
    authors: ['Prof. Boedi Harsono'],
    publisher: 'Trisakti',
    publishedDate: '2020',
    description: 'Kajian UUPA No. 5/1960, hak atas tanah, sertifikasi tanah, serta kepastian hukum pertanahan di Indonesia.',
    isbn: '978-979-8398-89-7',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Agraria',
    coverUrl: COVERS.agraria,
    pageCount: 590,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-05 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-06',
    title: 'Hukum Administrasi Negara & Good Governance',
    authors: ['Philipus M. Hadjon'],
    publisher: 'Gadjah Mada University Press',
    publishedDate: '2022',
    description: 'Analisis perbuatan pemerintah, keputusan fiktif positif, wewenang diskresi, dan perlindungan hukum bagi rakyat.',
    isbn: '978-979-420-771-0',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Administrasi',
    coverUrl: COVERS.administrasi,
    pageCount: 340,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-06 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-07',
    title: 'Hukum Lingkungan & Penegakan Hukum Ekologi',
    authors: ['Prof. Dr. Siti Sundari Reksodiputro'],
    publisher: 'Airlangga University Press',
    publishedDate: '2023',
    description: 'Prinsip pencemar membayar (polluter pays principle), AMDAL, serta instrumen hukum gugatan Lingkungan Hidup.',
    isbn: '978-602-473-102-1',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Lingkungan',
    coverUrl: COVERS.lingkungan,
    pageCount: 420,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-07 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-08',
    title: 'Hukum Ketenagakerjaan & Hubungan Industrial',
    authors: ['Lalu Husni, S.H., M.Hum.'],
    publisher: 'Rajawali Pers',
    publishedDate: '2021',
    description: 'Dinamika regulasi Cipta Kerja, hak PHK, pesangon, penetapan UMR, serta perselisihan hubungan industrial.',
    isbn: '978-602-425-889-4',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Perburuhan',
    coverUrl: COVERS.perdata,
    pageCount: 310,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-08 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-09',
    title: 'Hukum Dagang & Bisnis Modern',
    authors: ['Zaeni Asyhadie, S.H.'],
    publisher: 'Rajawali Pers',
    publishedDate: '2022',
    description: 'Perseroan Terbatas (PT), kepailitan, arbitrase bisnis, surat berharga, dan aspek hukum e-commerce di Indonesia.',
    isbn: '978-979-769-411-2',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Bisnis',
    coverUrl: COVERS.tataNegara,
    pageCount: 460,
    language: 'id',
    availability: 'DIPINJAM',
    shelfLocation: 'Rak H-09 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-10',
    title: 'Hukum Pajak & Keuangan Negara',
    authors: ['Prof. Dr. Rochmat Soemitro'],
    publisher: 'Refika Aditama',
    publishedDate: '2020',
    description: 'Konsep pemungutan pajak, sengketa pajak di Pengadilan Pajak, serta tindak pidana perpajakan.',
    isbn: '978-979-1073-88-2',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Keuangan',
    coverUrl: COVERS.administrasi,
    pageCount: 290,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-10 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-11',
    title: 'Sosiologi Hukum: Kajian Kemasyarakatan terhadap Hukum',
    authors: ['Prof. Dr. Soerjono Soekanto'],
    publisher: 'Rajawali Pers',
    publishedDate: '2021',
    description: 'Hubungan timbal balik antara perubahan sosial di masyarakat dengan kesadaran dan penegakan hukum.',
    isbn: '978-979-421-018-5',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Sosiologi Hukum',
    coverUrl: COVERS.politik,
    pageCount: 270,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-11 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-12',
    title: 'Hukum Adat Indonesia: Eksistensi & Pluralisme Hukum',
    authors: ['Prof. Bushar Muhammad, S.H.'],
    publisher: 'Pradnya Paramita',
    publishedDate: '2019',
    description: 'Kajian struktur persekutuan adat, hukum tanah adat, perkasawinan adat, dan hak ulayat di Nusantara.',
    isbn: '978-979-408-112-9',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Adat',
    coverUrl: COVERS.agraria,
    pageCount: 350,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-12 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-13',
    title: 'Hukum Kekayaan Intelektual (HKI) & Hak Cipta Digital',
    authors: ['Dr. OK. Saidin, S.H., M.Hum.'],
    publisher: 'Rajawali Pers',
    publishedDate: '2023',
    description: 'Perlindungan Hak Cipta, Paten, Merek, Rahasia Dagang, serta pelanggaran HKI di era internet.',
    isbn: '978-602-425-412-4',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum HKI',
    coverUrl: COVERS.administrasi,
    pageCount: 480,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-13 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-14',
    title: 'Hukum Perlindungan Konsumen di Indonesia',
    authors: ['Celina Tri Siwi Kristiyanti'],
    publisher: 'Sinar Grafika',
    publishedDate: '2022',
    description: 'Analisis UU No. 8/1999, tanggung jawab pelaku usaha, serta mekanisme penyelesaian sengketa konsumen (BPSK).',
    isbn: '978-979-007-312-0',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Konsumen',
    coverUrl: COVERS.perdata,
    pageCount: 260,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-14 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-15',
    title: 'Teori & Metodologi Penelitian Hukum Normatif-Empiris',
    authors: ['Prof. Dr. Peter Mahmud Marzuki'],
    publisher: 'Kencana',
    publishedDate: '2023',
    description: 'Metode riset akademis hukum, pendekatan perundang-undangan, pendekatan kasus, serta konseptualisasi hukum.',
    isbn: '978-602-7985-92-6',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Metode Riset Hukum',
    coverUrl: COVERS.acara,
    pageCount: 290,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-15 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-16',
    title: 'Hukum Pembuktian dalam Perkara Perdata',
    authors: ['M. Yahya Harahap, S.H.'],
    publisher: 'Sinar Grafika',
    publishedDate: '2022',
    description: 'Pembahasan alat bukti surat, saksi, persangkaan, pengakuan, dan sumpah di depan persidangan perdata.',
    isbn: '978-979-007-010-5',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Acara Perdata',
    coverUrl: COVERS.perdata,
    pageCount: 540,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-16 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-17',
    title: 'Hukum Kepailitan & Penundaan Kewajiban Pembayaran Utang (PKPU)',
    authors: ['Prof. Dr. Sutan Remy Sjahdeeni'],
    publisher: 'Pustaka Utama Grafiti',
    publishedDate: '2021',
    description: 'Kajian UU No. 37/2004, tugas kurator, pengurus PKPU, serta perdamaian sengketa utang piutang.',
    isbn: '978-979-444-411-9',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Kepailitan',
    coverUrl: COVERS.tataNegara,
    pageCount: 430,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-17 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-18',
    title: 'Hukum Perbankan & Lembaga Keuangan Syariah',
    authors: ['Dr. Hermansyah, S.H., M.Hum.'],
    publisher: 'Kencana',
    publishedDate: '2023',
    description: 'Regulasi OJK, rahasia bank, akad-akad syariah, dan penanganan kredit bermasalah.',
    isbn: '978-602-422-101-0',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Perbankan',
    coverUrl: COVERS.administrasi,
    pageCount: 380,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-18 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-19',
    title: 'Hukum Perlindungan Anak & Sistem Peradilan Pidana Anak',
    authors: ['Marlina, S.H., M.Hum.'],
    publisher: 'Refika Aditama',
    publishedDate: '2022',
    description: 'Konsep diversi, pendekatan restorative justice, serta perlindungan anak sebagai korban kejahatan.',
    isbn: '978-602-8650-12-8',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Perlindungan Anak',
    coverUrl: COVERS.pidana,
    pageCount: 260,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-19 (Lantai 2)',
    isInternational: false,
  },
  {
    id: 'hn-20',
    title: 'Hukum Kesehatan & Etika Kedokteran Indonesia',
    authors: ['Prof. Dr. Alexandra Indriyanti'],
    publisher: 'Rineka Cipta',
    publishedDate: '2021',
    description: 'Tanggung jawab hukum malpraktik medis, informed consent, dan hak-hak pasien dalam layanan kesehatan.',
    isbn: '978-979-518-990-0',
    category: 'HUKUM_NASIONAL',
    categoryLabel: 'Hukum Kesehatan',
    coverUrl: COVERS.administrasi,
    pageCount: 310,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak H-20 (Lantai 2)',
    isInternational: false,
  },

  // --- HUKUM INTERNASIONAL (12 BUKU) ---
  {
    id: 'hi-01',
    title: 'Principles of International Law & Global Governance',
    authors: ['Malcolm N. Shaw'],
    publisher: 'Cambridge University Press',
    publishedDate: '2021',
    description: 'An authoritative study on international treaties, state sovereignty, diplomatic immunity, and ICJ procedures.',
    isbn: '978-1108463119',
    category: 'HUKUM_INTERNASIONAL',
    categoryLabel: 'Hukum Internasional',
    coverUrl: COVERS.internasional,
    pageCount: 1120,
    language: 'en',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak HI-01 (Lantai 2)',
    isInternational: true,
  },
  {
    id: 'hi-02',
    title: 'International Law of the Sea (UNCLOS Framework)',
    authors: ['Rothwell & Stephens'],
    publisher: 'Hart Publishing',
    publishedDate: '2022',
    description: 'Comprehensive analysis on territorial seas, exclusive economic zones (EEZ), continental shelf, and maritime boundaries.',
    isbn: '978-1509923450',
    category: 'HUKUM_INTERNASIONAL',
    categoryLabel: 'Hukum Laut Internasional',
    coverUrl: COVERS.lingkungan,
    pageCount: 610,
    language: 'en',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak HI-02 (Lantai 2)',
    isInternational: true,
  },
  {
    id: 'hi-03',
    title: 'International Human Rights Law: Cases & Materials',
    authors: ['Rhona K.M. Smith'],
    publisher: 'Oxford University Press',
    publishedDate: '2023',
    description: 'Global human rights charters, United Nations treaty bodies, and regional human rights courts mechanism.',
    isbn: '978-0198860112',
    category: 'HUKUM_INTERNASIONAL',
    categoryLabel: 'HAM Internasional',
    coverUrl: COVERS.tataNegara,
    pageCount: 540,
    language: 'en',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak HI-03 (Lantai 2)',
    isInternational: true,
  },
  {
    id: 'hi-04',
    title: 'Diplomatic and Consular Law: Theory & Practice',
    authors: ['Eileen Denza'],
    publisher: 'Oxford University Press',
    publishedDate: '2020',
    description: 'In-depth analysis of the 1961 Vienna Convention on Diplomatic Relations and diplomatic immunity cases.',
    isbn: '978-0198795827',
    category: 'HUKUM_INTERNASIONAL',
    categoryLabel: 'Hukum Diplomatik',
    coverUrl: COVERS.internasional,
    pageCount: 490,
    language: 'en',
    availability: 'DIPINJAM',
    shelfLocation: 'Rak HI-04 (Lantai 2)',
    isInternational: true,
  },
  {
    id: 'hi-05',
    title: 'International Trade Law (WTO & ASEAN Economic Area)',
    authors: ['Trebilcock & Howse'],
    publisher: 'Routledge',
    publishedDate: '2022',
    description: 'Tariff disputes, anti-dumping regulations, and dispute settlement mechanisms under GATT/WTO.',
    isbn: '978-0415787420',
    category: 'HUKUM_INTERNASIONAL',
    categoryLabel: 'Hukum Perdagangan',
    coverUrl: COVERS.internasional,
    pageCount: 780,
    language: 'en',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak HI-05 (Lantai 2)',
    isInternational: true,
  },
  {
    id: 'hi-06',
    title: 'International Criminal Law & ICC Statute',
    authors: ['Antonio Cassese'],
    publisher: 'Oxford University Press',
    publishedDate: '2021',
    description: 'Jurisdiction of the International Criminal Court over genocide, war crimes, and crimes against humanity.',
    isbn: '978-0199694907',
    category: 'HUKUM_INTERNASIONAL',
    categoryLabel: 'Hukum Pidana Int.',
    coverUrl: COVERS.pidana,
    pageCount: 560,
    language: 'en',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak HI-06 (Lantai 2)',
    isInternational: true,
  },
  {
    id: 'hi-07',
    title: 'Hukum Perdata Internasional Indonesia',
    authors: ['Prof. Dr. Gautama, S.H.'],
    publisher: 'Alumni',
    publishedDate: '2020',
    description: 'Prinsip penunjukan hukum (choice of law), forum kontrak lintas negara, serta pengakuan putusan asing.',
    isbn: '978-979-414-012-3',
    category: 'HUKUM_INTERNASIONAL',
    categoryLabel: 'Hukum Perdata Int.',
    coverUrl: COVERS.perdata,
    pageCount: 430,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak HI-07 (Lantai 2)',
    isInternational: true,
  },
  {
    id: 'hi-08',
    title: 'International Environmental Treaties & Climate Law',
    authors: ['Patricia Birnie'],
    publisher: 'Oxford University Press',
    publishedDate: '2023',
    description: 'Paris Agreement, carbon trade regulations, and international responsibility for global biodiversity.',
    isbn: '978-0199228805',
    category: 'HUKUM_INTERNASIONAL',
    categoryLabel: 'Hukum Lingkungan Int.',
    coverUrl: COVERS.lingkungan,
    pageCount: 820,
    language: 'en',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak HI-08 (Lantai 2)',
    isInternational: true,
  },
  {
    id: 'hi-09',
    title: 'Cyber Law & Global Space Treaty Dynamics',
    authors: ['Dr. Michael N. Schmitt'],
    publisher: 'Cambridge University Press',
    publishedDate: '2022',
    description: 'Tallinn Manual 2.0 on international law applicable to cyber warfare and digital sovereignty.',
    isbn: '978-1107177222',
    category: 'HUKUM_INTERNASIONAL',
    categoryLabel: 'Cyber Law Global',
    coverUrl: COVERS.administrasi,
    pageCount: 600,
    language: 'en',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak HI-09 (Lantai 2)',
    isInternational: true,
  },
  {
    id: 'hi-10',
    title: 'Hukum Perjanjian Internasional (Vienna Convention 1969)',
    authors: ['Prof. Dr. Boer Mauna'],
    publisher: 'Alumni',
    publishedDate: '2021',
    description: 'Prosedur pembuatan traktat, peratifikasian UU di Indonesia, serta pengakhiran perjanjian internasional.',
    isbn: '978-979-414-220-2',
    category: 'HUKUM_INTERNASIONAL',
    categoryLabel: 'Hukum Traktat',
    coverUrl: COVERS.internasional,
    pageCount: 390,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak HI-10 (Lantai 2)',
    isInternational: true,
  },
  {
    id: 'hi-11',
    title: 'ASEAN Law & Regional Integration',
    authors: ['Walter Woon'],
    publisher: 'Edward Elgar Publishing',
    publishedDate: '2020',
    description: 'Legal personality of ASEAN Charter, dispute settlement mechanisms, and economic community rules.',
    isbn: '978-1788118026',
    category: 'HUKUM_INTERNASIONAL',
    categoryLabel: 'Hukum ASEAN',
    coverUrl: COVERS.tataNegara,
    pageCount: 330,
    language: 'en',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak HI-11 (Lantai 2)',
    isInternational: true,
  },
  {
    id: 'hi-12',
    title: 'International Humanitarian Law in Armed Conflicts',
    authors: ['Jean-Marie Henckaerts'],
    publisher: 'ICRC / Cambridge',
    publishedDate: '2022',
    description: 'Geneva Conventions 1949, protection of civilian populations, and customary international rules.',
    isbn: '978-0521839990',
    category: 'HUKUM_INTERNASIONAL',
    categoryLabel: 'Hukum Humaniter',
    coverUrl: COVERS.pidana,
    pageCount: 510,
    language: 'en',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak HI-12 (Lantai 2)',
    isInternational: true,
  },

  // --- POLITIK & PEMERINTAHAN (10 BUKU) ---
  {
    id: 'pol-01',
    title: 'Dasar-Dasar Ilmu Politik (Edisi Pemikiran Modern)',
    authors: ['Prof. Miriam Budiardjo'],
    publisher: 'Gramedia Pustaka Utama',
    publishedDate: '2023',
    description: 'Buku wajib induk ilmu politik: konsep kekuasaan, legitimasi, sistem pemerintahan, dan kelembagaan partai.',
    isbn: '978-979-22-8900-1',
    category: 'POLITIK_PEMERINTAHAN',
    categoryLabel: 'Ilmu Politik',
    coverUrl: COVERS.politik,
    pageCount: 520,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak P-01 (Lantai 1)',
    isInternational: false,
  },
  {
    id: 'pol-02',
    title: 'Sistem Politik Indonesia: Dinamika Demokrasi Pasca-Reformasi',
    authors: ['Prof. Dr. Afan Gaffar'],
    publisher: 'Pustaka Pelajar',
    publishedDate: '2021',
    description: 'Pergeseran peta politik lokal, oligarki politik, presidensialisme, dan perilaku pemilih Indonesia.',
    isbn: '978-979-9289-12-8',
    category: 'POLITIK_PEMERINTAHAN',
    categoryLabel: 'Politik Indonesia',
    coverUrl: COVERS.tataNegara,
    pageCount: 360,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak P-02 (Lantai 1)',
    isInternational: false,
  },
  {
    id: 'pol-03',
    title: 'Otonomi Daerah & Desentralisasi Pemerintahan',
    authors: ['Prof. Ryaas Rasyid'],
    publisher: 'Masyarakat Transparansi Indonesia',
    publishedDate: '2020',
    description: 'Kajian transfer daerah, pembagian kewenangan pusat-daerah, serta akuntabilitas tata kelola lokal.',
    isbn: '978-979-9602-01-3',
    category: 'POLITIK_PEMERINTAHAN',
    categoryLabel: 'Otonomi Daerah',
    coverUrl: COVERS.administrasi,
    pageCount: 310,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak P-03 (Lantai 1)',
    isInternational: false,
  },
  {
    id: 'pol-04',
    title: 'Politik Hukum Pembaruan Agraria & Sumber Daya Alam',
    authors: ['Prof. Mahfud MD'],
    publisher: 'Rajawali Pers',
    publishedDate: '2022',
    description: 'Pengaruh konfigurasi politik otoriter vs demokratis terhadap produk hukum pertanahan dan kehutanan.',
    isbn: '978-979-769-201-1',
    category: 'POLITIK_PEMERINTAHAN',
    categoryLabel: 'Politik Hukum',
    coverUrl: COVERS.agraria,
    pageCount: 450,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak P-04 (Lantai 1)',
    isInternational: false,
  },
  {
    id: 'pol-05',
    title: 'Kebijakan Publik: Formulasi, Implementasi & Evaluasi',
    authors: ['Prof. Dr. Riant Nugroho'],
    publisher: 'Elex Media Komputindo',
    publishedDate: '2023',
    description: 'Metodologi pembuatan kebijakan publik yang efektif, analisis dampaknya, dan mitigasi kegagalan publik.',
    isbn: '978-602-048-911-2',
    category: 'POLITIK_PEMERINTAHAN',
    categoryLabel: 'Kebijakan Publik',
    coverUrl: COVERS.politik,
    pageCount: 620,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak P-05 (Lantai 1)',
    isInternational: false,
  },
  {
    id: 'pol-06',
    title: 'Sistem Pemilu & Hukum Kepemiluan Indonesia',
    authors: ['Ramlan Surbakti, Ph.D.'],
    publisher: 'Kemitraan',
    publishedDate: '2023',
    description: 'Penyelenggaraan Pemilu serentak, ambang batas parlemen (parliamentary threshold), dan penanganan sengketa Pemilu.',
    isbn: '978-602-140-022-8',
    category: 'POLITIK_PEMERINTAHAN',
    categoryLabel: 'Hukum Pemilu',
    coverUrl: COVERS.tataNegara,
    pageCount: 380,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak P-06 (Lantai 1)',
    isInternational: false,
  },
  {
    id: 'pol-07',
    title: 'Geopolitik & Keamanan Nasional di Asia Tenggara',
    authors: ['Banyu Perwita, Ph.D.'],
    publisher: 'Rosda',
    publishedDate: '2021',
    description: 'Peta pertahanan kawasan Laut China Selatan, posisi strategis Indonesia, dan diplomasi pertahanan.',
    isbn: '978-979-692-411-9',
    category: 'POLITIK_PEMERINTAHAN',
    categoryLabel: 'Geopolitik',
    coverUrl: COVERS.internasional,
    pageCount: 290,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak P-07 (Lantai 1)',
    isInternational: false,
  },
  {
    id: 'pol-08',
    title: 'Partai Politik & Komunikasi Politik Digital',
    authors: ['Prof. Burhan Muhtadi, Ph.D.'],
    publisher: 'Kepustakaan Populer Gramedia',
    publishedDate: '2023',
    description: 'Pengaruh media sosial, algoritma kampanye, dan pola partisipasi politik pemilih pemula di Indonesia.',
    isbn: '978-602-481-220-1',
    category: 'POLITIK_PEMERINTAHAN',
    categoryLabel: 'Komunikasi Politik',
    coverUrl: COVERS.politik,
    pageCount: 340,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak P-08 (Lantai 1)',
    isInternational: false,
  },
  {
    id: 'pol-09',
    title: 'Birokratisasi & Tata Kelola Pemerintahan Bersih',
    authors: ['Eko Prasojo, Ph.D.'],
    publisher: 'UI Publishing',
    publishedDate: '2021',
    description: 'Reformasi birokrasi, digitalisasi pelayanan publik (e-government), dan pencegahan tindak pidana korupsi.',
    isbn: '978-979-456-880-1',
    category: 'POLITIK_PEMERINTAHAN',
    categoryLabel: 'Birokrasi Publik',
    coverUrl: COVERS.administrasi,
    pageCount: 310,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak P-09 (Lantai 1)',
    isInternational: false,
  },
  {
    id: 'pol-10',
    title: 'Comparative Politics: Institutions and Behavior',
    authors: ['Patrick H. O\'Neil'],
    publisher: 'W. W. Norton & Company',
    publishedDate: '2022',
    description: 'Comparative analysis of democratic regimes, authoritarian states, and political economies around the world.',
    isbn: '978-0393675474',
    category: 'POLITIK_PEMERINTAHAN',
    categoryLabel: 'Politik Komparatif',
    coverUrl: COVERS.politik,
    pageCount: 580,
    language: 'en',
    availability: 'TERSEDIA',
    shelfLocation: 'Rak P-10 (Lantai 1)',
    isInternational: true,
  },

  // --- RISET & JURNAL KALTIM / IKN / FH UWGM (10 BUKU) ---
  {
    id: 'rs-01',
    title: 'Analisis Yuridis Efektivitas Penegakan Hukum Lingkungan Pertambangan di Kalimantan Timur',
    authors: ['Tim Peneliti Fakultas Hukum UWGM Samarinda'],
    publisher: 'Jurnal Hukum Widya Gama Mahakam',
    publishedDate: '2024',
    description: 'Riset akademis komprehensif mengenai pertanggungjawaban reklamasi pascamptambang batubara dan hak ekologis warga Samarinda.',
    isbn: 'JRN-UWGM-2024-01',
    category: 'RISET_JURNAL',
    categoryLabel: 'Jurnal Riset Law',
    coverUrl: COVERS.lingkungan,
    pageCount: 94,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Arsip Riset Digital (Lantai 3)',
    isInternational: false,
  },
  {
    id: 'rs-02',
    title: 'Implikasi Hukum Tata Ruang & Pertanahan Pasca-Penetapan Ibu Kota Nusantara (IKN)',
    authors: ['Dr. Sudirman, S.H., M.H. & Tim FH UWGM'],
    publisher: 'Jurnal Hukum Widya Gama Mahakam',
    publishedDate: '2024',
    description: 'Kajian yuridis UU No. 21/2023 tentang IKN terhadap perlindungan hak atas tanah adat masyarakat lokal Penajam Paser Utara.',
    isbn: 'JRN-UWGM-2024-02',
    category: 'RISET_JURNAL',
    categoryLabel: 'Riset IKN Nusantara',
    coverUrl: COVERS.agraria,
    pageCount: 112,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Arsip Riset Digital (Lantai 3)',
    isInternational: false,
  },
  {
    id: 'rs-03',
    title: 'Perlindungan Hukum Hak Ulayat Masyarakat Adat Dayak dalam Pengelolaan Hutan Kaltim',
    authors: ['Pusat Studi Hukum & Hak Asasi Manusia UWGM'],
    publisher: 'Jurnal Kebijakan & Hukum Mahakam',
    publishedDate: '2023',
    description: 'Studi empiris inventarisasi tanah ulayat dan kepastian hukum penetapan hutan adat di Kabupaten Kutai Barat.',
    isbn: 'JRN-UWGM-2023-08',
    category: 'RISET_JURNAL',
    categoryLabel: 'Riset Hukum Adat',
    coverUrl: COVERS.pidana,
    pageCount: 88,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Arsip Riset Digital (Lantai 3)',
    isInternational: false,
  },
  {
    id: 'rs-04',
    title: 'Pencegahan Tindak Pidana Korupsi Sektor Perizinan SDA di Pemerintah Daerah Kalimantan Timur',
    authors: ['Laboratorium Hukum Pidana FH UWGM'],
    publisher: 'Jurnal Integritas Hukum Samarinda',
    publishedDate: '2023',
    description: 'Evaluasi penerapan Online Single Submission (OSS) dalam meminimalisir suap perizinan IUP batubara.',
    isbn: 'JRN-UWGM-2023-11',
    category: 'RISET_JURNAL',
    categoryLabel: 'Riset Anti-Korupsi',
    coverUrl: COVERS.administrasi,
    pageCount: 105,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Arsip Riset Digital (Lantai 3)',
    isInternational: false,
  },
  {
    id: 'rs-05',
    title: 'Penyelesaian Sengketa Hubungan Industrial melalui Mediasi di Kota Samarinda',
    authors: ['Dosen Pengampu Klinik Hukum FH UWGM'],
    publisher: 'Jurnal Peradilan & Arbitrase Mahakam',
    publishedDate: '2024',
    description: 'Efektivitas peran Disnakertrans Samarinda dalam menangani perselisihan pemutusan hubungan kerja sektor industri hilir.',
    isbn: 'JRN-UWGM-2024-03',
    category: 'RISET_JURNAL',
    categoryLabel: 'Riset Hukum Kerja',
    coverUrl: COVERS.perdata,
    pageCount: 76,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Arsip Riset Digital (Lantai 3)',
    isInternational: false,
  },
  {
    id: 'rs-06',
    title: 'Analisis Legalitas Transaksi Kripto & Smart Contracts di Indonesia',
    authors: ['Pusat Studi Hukum Bisnis Digital UWGM'],
    publisher: 'Jurnal Hukum & Teknologi Kaltim',
    publishedDate: '2023',
    description: 'Ditinjau dari UU ITE, KUHPerdata, serta Peraturan Bappebti mengenai aset kripto sebagai komoditas perdagangan.',
    isbn: 'JRN-UWGM-2023-14',
    category: 'RISET_JURNAL',
    categoryLabel: 'Riset Cyber Law',
    coverUrl: COVERS.administrasi,
    pageCount: 130,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Arsip Riset Digital (Lantai 3)',
    isInternational: false,
  },
  {
    id: 'rs-07',
    title: 'Eksistensi Mahkamah Konstitusi dalam Pengujian UU Cipta Kerja',
    authors: ['Jurnal Hukum Tata Negara UWGM'],
    publisher: 'Buku Bunga Rampai Dosen FH UWGM',
    publishedDate: '2022',
    description: 'Analisis putusan Inskonstitusional Bersyarat dan implikasinya terhadap pembentukan peraturan perundang-undangan.',
    isbn: 'JRN-UWGM-2022-09',
    category: 'RISET_JURNAL',
    categoryLabel: 'Riset Konstitusi',
    coverUrl: COVERS.tataNegara,
    pageCount: 150,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Arsip Riset Digital (Lantai 3)',
    isInternational: false,
  },
  {
    id: 'rs-08',
    title: 'Tinjauan Kriminologi terhadap Kejahatan Siber di Wilayah Hukum Polda Kaltim',
    authors: ['Laboratorium Kriminologi FH UWGM'],
    publisher: 'Jurnal Hukum Pidana & Criminology',
    publishedDate: '2024',
    description: 'Modus operandi penipuan online, kebocoran data pribadi, dan efektivitas penindakan tim Siber Ditreskrimsus.',
    isbn: 'JRN-UWGM-2024-05',
    category: 'RISET_JURNAL',
    categoryLabel: 'Riset Kriminologi',
    coverUrl: COVERS.pidana,
    pageCount: 82,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Arsip Riset Digital (Lantai 3)',
    isInternational: false,
  },
  {
    id: 'rs-09',
    title: 'Legal Aspect of Coal Transportation in Mahakam River Basin',
    authors: ['FH UWGM Environmental Law Department'],
    publisher: 'International Journal of Borneo Legal Studies',
    publishedDate: '2023',
    description: 'Study on environmental liability regarding vessel collisions and coal dust pollution along the Mahakam river.',
    isbn: 'JRN-UWGM-2023-22',
    category: 'RISET_JURNAL',
    categoryLabel: 'Riset Sungai Mahakam',
    coverUrl: COVERS.lingkungan,
    pageCount: 90,
    language: 'en',
    availability: 'TERSEDIA',
    shelfLocation: 'Arsip Riset Digital (Lantai 3)',
    isInternational: true,
  },
  {
    id: 'rs-10',
    title: 'Penataan Batas Wilayah Antar-Kabupaten di Kalimantan Timur Pasca Pemekaran',
    authors: ['Pusat Otonomi Daerah FH UWGM'],
    publisher: 'Jurnal Pemerintahan & Hukum Lokal',
    publishedDate: '2022',
    description: 'Mekanisme mediasi Kemendagri dalam menetapkan pilar batas wilayah Kutai Kartanegara dan Samarinda.',
    isbn: 'JRN-UWGM-2022-15',
    category: 'RISET_JURNAL',
    categoryLabel: 'Riset Otda Kaltim',
    coverUrl: COVERS.agraria,
    pageCount: 110,
    language: 'id',
    availability: 'TERSEDIA',
    shelfLocation: 'Arsip Riset Digital (Lantai 3)',
    isInternational: false,
  }
];

export async function fetchLegalBooks(query: string = '', category: LegalCategory = 'ALL'): Promise<BookItem[]> {
  // Simulasi network delay tipis (100ms) agar transisi UX terasa natural
  await new Promise(resolve => setTimeout(resolve, 100));

  let results = FULL_LEGAL_DATABASE;

  // Filter berdasarkan Kategori
  if (category !== 'ALL') {
    results = results.filter(book => book.category === category);
  }

  // Filter berdasarkan Kata Kunci Pencarian
  if (query && query.trim() !== '') {
    const q = query.toLowerCase().trim();
    results = results.filter(
      book =>
        book.title.toLowerCase().includes(q) ||
        book.authors.some(a => a.toLowerCase().includes(q)) ||
        book.description.toLowerCase().includes(q) ||
        book.categoryLabel.toLowerCase().includes(q) ||
        book.isbn.toLowerCase().includes(q)
    );
  }

  return results;
}